# Generated by Django 2.2.13 on 2020-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('phone_repair', 'Ремонт мобильных телефонов'), ('plumbing', 'Сантехника'), ('tv_repair', 'Ремонт телевизоров'), ('buy_sell', 'Купи-продай')], default='other', max_length=50, verbose_name='Категории'),
        ),
    ]
